"""initial tables

Revision ID: 38d814fe064a
Revises: 
Create Date: 2026-03-25 16:19:00.811533
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38d814fe064a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infrastructure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('infra_type', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('locality', sa.String(length=200), nullable=True),
    sa.Column('ward', sa.String(length=100), nullable=True),
    sa.Column('pin_code', sa.String(length=10), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('census_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('density_per_sqkm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('growth_rate_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('households', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('masterplans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('zoning_type', sa.String(length=100), nullable=True),
    sa.Column('fsi', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('ground_coverage_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_height_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('setback_front_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('setback_side_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('price_per_sqft', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valuation_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('land_value_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('development_potential_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('future_appreciation_index', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('infra_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('price_trend_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('zoning_favorability', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('density_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('valuation_scores')
    op.drop_table('property_prices')
    op.drop_table('masterplans')
    op.drop_table('census_data')
    op.drop_index('idx_locations_geom', table_name='locations', postgresql_using='gist')
    op.drop_table('locations')
    op.drop_index('idx_infra_geom', table_name='infrastructure', postgresql_using='gist')
    op.drop_table('infrastructure')
    # ### end Alembic commands ###
